#ifndef WS_CONFIG_H
#define WS_CONFIG_H

#define WS_WIFI_SSID "YOUR_SSID"
#define WS_WIFI_PASSWORD "YOUR_PASSWORD"
#define WS_MQTT_SERVER "MQTT_SERVER"
#define WS_MQTT_USER "MQTT_USER"
#define WS_MQTT_PASSWORD "MQTT_PASSWORD"
#define WS_MQTT_CHANNEL_ID 0
#define WS_MQTT_READ_API_KEY "MQTT_READ_API_KEY"
#define WS_MQTT_WRITE_API_KEY "MQTT_WRITE_API_KEY"

#endif